epochs: -1
accelerator: gpu
steps: 375000
warmup_steps: 100000
ema_decay: 0.999
ema_end_decay : 0.99999
ema_anneal_end_step: 100000
precision: bf16-mixed
compile_modules: False
num_gpus : 1
size : base
average_top_k_layers : 8
use_rope_encoder : True 
use_rope_decoder : True
use_kernel_dropout_encoder : True
use_kernel_dropout_decoder : True