name: transformer

transformer_decoder_layers_cfg:
  d_model: 384           
  nhead: 6             
  batch_first: true
  norm_first: false      
  bias: true
  mlp_ratio: 4.0
  dropout: 0.0   
  activation: gelu
  layer_norm_eps: 1.0e-6

transformer_decoder_cfg:
  num_layers: 4
  enable_nested_tensor: false
  mask_check: true